# Generated by Django 5.2 on 2025-05-03 14:41

import event.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event/thumbnails'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/images', validators=[event.validators.validate_image_format]),
        ),
    ]
